[workspace]
authors = ["shivasankar <shivasankar.ka@gmail.com>"]
channels = [
    "https://conda.modular.com/max",
    "conda-forge",
    "https://conda.modular.com/max-nightly/",
    "https://repo.prefix.dev/modular-community",
]
platforms = ["osx-arm64", "linux-64"]
preview = ["pixi-build"]

[tasks]
format = "mojo format ./scijo && mojo format ./tests && mojo format ./benchmark"
package = "mojo precompile scijo && cp scijo.mojoc tests/"

[dependencies]
mojo = ">=1.0.0b2,<2"
msl = {git = "https://github.com/mojomath/MSL.git", branch = "main"}
numojo = { git = "https://github.com/Mojo-Numerics-and-Algorithms-group/NuMojo.git", branch = "main"}

[package]
name = "scijo"
version = "0.2.0"

[package.build]
backend = { name = "pixi-build-mojo", version = "0.*"}

[package.build.config.pkg]
name = "scijo"

[package.host-dependencies]
mojo = "==1.0.0b1"
msl = {git = "https://github.com/mojomath/MSL.git", branch = "main"}
numojo = { git = "https://github.com/Mojo-Numerics-and-Algorithms-group/NuMojo.git", branch = "main"}

[package.build-dependencies]
mojo = "==1.0.0b1"
msl = {git = "https://github.com/mojomath/MSL.git", branch = "main"}
numojo = { git = "https://github.com/Mojo-Numerics-and-Algorithms-group/NuMojo.git", branch = "main"}

[package.run-dependencies]
mojo = "==1.0.0b1"
msl = {git = "https://github.com/mojomath/MSL.git", branch = "main"}
numojo = { git = "https://github.com/Mojo-Numerics-and-Algorithms-group/NuMojo.git", branch = "main"}

[feature.test.dependencies]
python = ">=3.14.6,<3.15"
scipy = ">=1.18.0,<2"
numpy = ">=2.5.1,<3"

[feature.test.tasks]
package = "mojo precompile scijo && cp scijo.mojoc tests/"
tests = { depends-on = ["package"], cmd = "bash ./tests/test_all.sh" }
final = { depends-on = ["package"], cmd = "mojo format ./scijo && mojo format ./tests && bash tests/test_all.sh" }

[environments]
test = ["test"]
